name: 'Receptura akcji dockera'
description: 'Pozdrow kogos'

inputs:
  who-to-greet:
    description: 'Kogo pozdrwic'
    required: True
    default: 'Świecie'
outputs:
  answer:
    description: 'Odpowiedź na wszystko (zawsze 42)'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
